# Generated by Django 6.0 on 2025-12-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user_text', models.TextField()),
                ('bot_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('fir', 'FIR'), ('bail', 'Bail'), ('legal_aid', 'Legal Aid'), ('case_status', 'Case Status'), ('other', 'Other')], default='other', max_length=50)),
                ('keywords', models.TextField(help_text='Comma-separated keywords, e.g. fir, first information report, police complaint')),
            ],
        ),
    ]
